# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/v23.1/FEB_fabric/FEB_fabric.runs/synth_1/FEB_fabric.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param simulator.modelsimInstallPath C:/intelFPGA/20.1/modelsim_ae/win32aloem
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/v23.1/FEB_fabric/FEB_fabric.cache/wt [current_project]
set_property parent.project_path C:/v23.1/FEB_fabric/FEB_fabric.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/mrigatti/AppData/Roaming/Xilinx/Vivado/2022.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:arty-s7-50:part0:1.1 [current_project]
set_property ip_repo_paths c:/v23.1/feb_fabric [current_project]
update_ip_catalog
set_property ip_output_repo c:/v23.1/FEB_fabric/FEB_fabric.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/AFEemu.coe
read_vhdl -library work {
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/Proj_Def.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/AFE_DataPath.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/AFE_Interface_Sim.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/AFE_Pipeline.vhd
  {C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/DDR_Interface .vhd}
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/EventBuilder.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/Exclude_EVB.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/Trigger.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/FEB_top_ARTY.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/Exclude_DDR.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/FM_Deserializer.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/FM_Serializer.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/Phase_Detector.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/One_Wire.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/Histogram.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/GPIO_emu.vhd
  C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/new/LVDS_TX.vhd
}
read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/feb_arty.tmp/feb_fabric_v1_0_project/FEB_fabric_v1_0_project.gen/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/feb_arty.tmp/feb_fabric_v1_0_project/FEB_fabric_v1_0_project.gen/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/feb_arty.tmp/feb_fabric_v1_0_project/FEB_fabric_v1_0_project.gen/sources_1/ip/DPRAM_1Kx16/DPRAM_1Kx16_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/feb_arty.tmp/feb_fabric_v1_0_project/FEB_fabric_v1_0_project.gen/sources_1/ip/AFE_DP_Pipeline/AFE_DP_Pipeline_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/DDR3LController/DDR3LController.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/ARTY.gen/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/ARTY.gen/sources_1/ip/DDR3LController/DDR3LController/user_design/constraints/DDR3LController_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0.xci
set_property used_in_synthesis false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila1/AFE_DataPath_ila1.xci
set_property used_in_synthesis false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila1/AFE_DataPath_ila1_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila2/AFE_DataPath_ila2.xci
set_property used_in_synthesis false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila2/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila2/AFE_DataPath_ila2_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/AFE_DataPath_ila3/AFE_DataPath_ila3.xci
set_property used_in_synthesis false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila3/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila3/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila3/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFE_DataPath_ila3/AFE_DataPath_ila3_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/AFEemu/AFEemu.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFEemu/AFEemu_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/AFEemu_ila/AFEemu_ila.xci
set_property used_in_synthesis false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFEemu_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFEemu_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFEemu_ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/AFEemu_ila/AFEemu_ila_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/EVB_ila0/EVB_ila0.xci
set_property used_in_synthesis false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/EVB_ila0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/EVB_ila0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/EVB_ila0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/EVB_ila0/EVB_ila0_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/Hist_Ram/Hist_Ram.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/Hist_Ram/Hist_Ram_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/LVDSTxBuff/LVDSTxBuff.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/LVDSTxBuff/LVDSTxBuff.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/LVDSTxBuff/LVDSTxBuff_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/Trigger_ila/Trigger_ila.xci
set_property used_in_synthesis false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/Trigger_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/Trigger_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/Trigger_ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/Trigger_ila/Trigger_ila_ooc.xdc]

read_ip -quiet C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/iuCD_FIFO/iuCD_FIFO_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/iuCD_FIFO/iuCD_FIFO_ooc.xdc]

read_ip -quiet c:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/DDR_ila_0/DDR_ila_0.xci
set_property used_in_synthesis false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/DDR_ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/DDR_ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/DDR_ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/DDR_ila_0/DDR_ila_0_ooc.xdc]

read_ip -quiet c:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128.xci
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/FIFO_128x128/FIFO_128x128.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/FIFO_128x128/FIFO_128x128_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/FIFO_128x128/FIFO_128x128_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/v23.1/FEB_fabric/FEB_fabric.srcs/constrs_1/new/pinout.xdc
set_property used_in_implementation false [get_files C:/v23.1/FEB_fabric/FEB_fabric.srcs/constrs_1/new/pinout.xdc]

read_xdc C:/v23.1/FEB_fabric/FEB_fabric.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files C:/v23.1/FEB_fabric/FEB_fabric.srcs/constrs_1/new/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/v23.1/FEB_fabric/FEB_fabric.srcs/utils_1/imports/synth_1/FEB_fabric.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top FEB_fabric -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FEB_fabric.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FEB_fabric_utilization_synth.rpt -pb FEB_fabric_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
