# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128.xci
# IP: The module: 'FIFO_128x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/FIFO_128x128/FIFO_128x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_128x128'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/FIFO_128x128/FIFO_128x128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_128x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/FIFO_128x128/FIFO_128x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_128x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128.xci
# IP: The module: 'FIFO_128x128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/FIFO_128x128/FIFO_128x128.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_128x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/FIFO_128x128/FIFO_128x128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_128x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/FIFO_128x128/FIFO_128x128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_128x128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
