# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xci
# IP: The module: 'iuCD_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'iuCD_FIFO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/iuCD_FIFO/iuCD_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'iuCD_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/iuCD_FIFO/iuCD_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iuCD_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/v23.1/FEB_fabric/FEB_fabric.srcs/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xci
# IP: The module: 'iuCD_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/iuCD_FIFO/iuCD_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'iuCD_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/iuCD_FIFO/iuCD_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'iuCD_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_fabric/FEB_fabric.gen/sources_1/ip/iuCD_FIFO/iuCD_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iuCD_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
