# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# Block Designs: bd/TestDDR/TestDDR.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestDDR || ORIG_REF_NAME==TestDDR} -quiet] -quiet

# IP: bd/TestDDR/ip/TestDDR_clk_wiz_0_2/TestDDR_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestDDR_clk_wiz_0_2 || ORIG_REF_NAME==TestDDR_clk_wiz_0_2} -quiet] -quiet

# IP: bd/TestDDR/ip/TestDDR_TestDDR_top_0_0/TestDDR_TestDDR_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestDDR_TestDDR_top_0_0 || ORIG_REF_NAME==TestDDR_TestDDR_top_0_0} -quiet] -quiet

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/DDR3LController/DDR3LController.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] -quiet

# IP: ip/SCFIFO_32x256/SCFIFO_32x256.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_32x256 || ORIG_REF_NAME==SCFIFO_32x256} -quiet] -quiet

# XDC: c:/v23.1/Test_DDR_Arty/Test_DDR_Arty.gen/sources_1/bd/TestDDR/TestDDR_ooc.xdc
