# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/bd/TestDDR/ip/TestDDR_TestDDR_top_0_0/TestDDR_TestDDR_top_0_0.xci
# IP: The module: 'TestDDR_TestDDR_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/DDR3LController/DDR3LController.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_128x128 || ORIG_REF_NAME==FIFO_128x128} -quiet] -quiet

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] -quiet

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/bd/TestDDR/ip/TestDDR_TestDDR_top_0_0/TestDDR_TestDDR_top_0_0.xci
# IP: The module: 'TestDDR_TestDDR_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/ila_0/ila_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/DDR3LController/DDR3LController.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3LController || ORIG_REF_NAME==DDR3LController} -quiet] -quiet

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/FIFO_128x128/FIFO_128x128.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_128x128 || ORIG_REF_NAME==FIFO_128x128} -quiet] -quiet

# IP: C:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/SCFIFO_1Kx16/SCFIFO_1Kx16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCFIFO_1Kx16 || ORIG_REF_NAME==SCFIFO_1Kx16} -quiet] -quiet
