# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xci
# IP: The module: 'SCFIFO_32x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/Test_DDR_Arty/Test_DDR_Arty.gen/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCFIFO_32x256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/Test_DDR_Arty/Test_DDR_Arty.gen/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCFIFO_32x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/Test_DDR_Arty/Test_DDR_Arty.gen/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCFIFO_32x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/v23.1/Test_DDR_Arty/Test_DDR_Arty.srcs/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xci
# IP: The module: 'SCFIFO_32x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/Test_DDR_Arty/Test_DDR_Arty.gen/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCFIFO_32x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/Test_DDR_Arty/Test_DDR_Arty.gen/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCFIFO_32x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/Test_DDR_Arty/Test_DDR_Arty.gen/sources_1/ip/SCFIFO_32x256/SCFIFO_32x256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'SCFIFO_32x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
